@startuml
hide circle
skinparam classAttributeIconSize 0

class Car {
    - id: int
    - make: string
    - model: string
    - year: int
    - color: string
    - price: double
    + __construct(id: int, make: string, model: string, year: int, color: string, price: double): void
    + getId(): int
    + setId(id: int): void
    + getMake(): string
    + setMake(make: string): void
    + getModel(): string
    + setModel(model: string): void
    + getYear(): int
    + setYear(year: int): void
    + getColor(): string
    + setColor(color: string): void
    + getPrice(): double
    + setPrice(price: double): void
}
@enduml
