@startuml
hide circle
skinparam classAttributeIconSize 0

class Customer {
    - id: int
    - firstName: string
    - lastName: string
    - phone: string
    - email: string
    - address: string
    + __construct(id: int, firstName: string, lastName: string, phone: string, email: string, address: string): void
    + getId(): int
    + setId(id: int): void
    + getFirstName(): string
    + setFirstName(firstName: string): void
    + getLastName(): string
    + setLastName(lastName: string): void
    + getPhone(): string
    + setPhone(phone: string): void
    + getEmail(): string
    + setEmail(email: string): void
    + getAddress(): string
    + setAddress(address: string): void
}
@enduml
