@startuml
hide circle
skinparam classAttributeIconSize 0

class DB {
    - db: PDO
    + __construct(): void
    - prepare(sql: string, params: array): PDOStatement | false
    - select(tableName: string, id: int, columns: array): array | null
    - insert(tableName: string, values: array): string | false
    - update(tableName: string, values: array): boolean
    - delete(tableName: string, id: int): boolean
    + insertCar(car: Car): string | false
    + readCar(id: int): Car | null
    + updateCar(car: Car): boolean
    + deleteCar(id: int): boolean
    + insertCustomer(customer: Customer): string | false
    + readCustomer(id: int): Customer | null
    + updateCustomer(customer: Customer): boolean
    + deleteCustomer(id: int): boolean
    + insertSalesperson(salesperson: Salesperson): string | false
    + readSalesperson(id: int): Salesperson | null
    + updateSalesperson(salesperson: Salesperson): boolean
    + deleteSalesperson(id: int): boolean
}
@enduml
