@startuml
hide circle
skinparam classAttributeIconSize 0

class Salesperson {
    - id: int
    - firstName: string
    - lastName: string
    - hireDate: string
    - salary: double
    - commissionPercent: double
    + __construct(id: int, firstName: string, lastName: string, hireDate: string, salary: double, commissionPercent: double): void
    + getId(): int
    + setId(id: int): void
    + getFirstName(): string
    + setFirstName(firstName: string): void
    + getLastName(): string
    + setLastName(lastName: string): void
    + getHireDate(): string
    + setHireDate(hireDate: string): void
    + getSalary(): double
    + setSalary(salary: double): void
    + getCommissionPercent(): double
    + setCommissionPercent(commissionPercent: double): void
}
@enduml
