@startuml
hide circle
skinparam classAttributeIconSize 0

class Salesperson {
    - id: int
    - firstName: string
    - lastName: string
    - hireDate: string
    - salary: double
    - commissionPercent: double
    + __construct(int, string, string, string, double, double): Salesperson
    + getId(): int
    + setId(int): void
    + getFirstName(): string
    + setFirstName(string): void
    + getLastName(): string
    + setLastName(string): void
    + getHireDate(): string
    + setHireDate(string): void
    + getSalary(): double
    + setSalary(double): void
    + getCommissionPercent(): double
    + setCommissionPercent(double): void
}
@enduml
